# Generated by Django 5.0.2 on 2024-02-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id_document', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.IntegerField()),
                ('url_document', models.CharField(max_length=255)),
                ('isdocument_vehicle', models.BooleanField()),
                ('isverified_document', models.BooleanField(default=False)),
                ('type_document', models.CharField(choices=[('CC', 'CC'), ('SOAT', 'SOAT'), ('LICENCIA', 'LICENCIA'), ('OPERACION', 'OPERACION'), ('TECNOMECANICA', 'TECNOMECANICA'), ('RECIBO', 'RECIBO')], max_length=15)),
                ('dateregister_document', models.DateTimeField(auto_now_add=True)),
                ('dateupdate_document', models.DateTimeField(auto_now=True)),
                ('dateverified_document', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'document',
            },
        ),
    ]
