# Generated by Django 5.0.2 on 2024-02-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('name_servicio', models.CharField(max_length=45)),
                ('image_servicio', models.ImageField(max_length=255, upload_to='imgservicio')),
                ('detail_servicio', models.TextField(max_length=500)),
            ],
        ),
    ]
