# Generated by Django 4.2.7 on 2024-02-07 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_User',
            fields=[
                ('id_Acount_User', models.AutoField(primary_key=True, serialize=False)),
                ('email_Account_User', models.EmailField(max_length=45, unique=True)),
                ('password_Account_User', models.CharField(max_length=255)),
                ('dateregister_Account_User', models.DateField(auto_now_add=True)),
                ('dateupdate_Account_User', models.DateField(auto_now=True)),
                ('isadmin_Acount_User', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mandadero',
            fields=[
                ('id_Mandadero', models.AutoField(primary_key=True, serialize=False)),
                ('name_Mandadero', models.CharField(max_length=45)),
                ('lastName_Mandadero', models.CharField(max_length=45)),
                ('phone_Mandadero', models.CharField(max_length=10)),
                ('image_Mandadero', models.ImageField(max_length=255, upload_to='imgMandadero')),
                ('ishavecar_Mandadero', models.BooleanField()),
                ('ishavemoto_Mandadero', models.BooleanField()),
                ('isactive_Mandadero', models.BooleanField(default=True)),
                ('isvalidate_Mandadero', models.BooleanField(default=True)),
                ('dateregister_Mandadero', models.DateTimeField(auto_now_add=True)),
                ('dateupdate_Mandadero', models.DateTimeField(auto_now=True)),
                ('address_Mandadero', models.CharField(max_length=100)),
                ('cc_Mandadero', models.CharField(max_length=13)),
                ('id_Account_User_Mandadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wsmandadero.account_user')),
            ],
        ),
    ]
