# Generated by Django 5.0.2 on 2024-03-02 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsmandadero', '0004_alter_mander_user_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmanager',
            name='request_id_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wsmandadero.request', unique=True),
        ),
    ]
