# Generated by Django 5.0.2 on 2024-03-02 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsmandadero', '0005_alter_requestmanager_request_id_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmanager',
            name='mander_id_mander',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='wsmandadero.mander'),
            preserve_default=False,
        ),
    ]
