# Generated by Django 5.0.2 on 2024-03-04 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsmandadero', '0003_alter_vehicle_image_vehicle'),
        ('wsmandadero', '0006_alter_requestmanager_mander_id_mander'),
    ]

    operations = [
    ]
