# Generated by Django 5.0.2 on 2024-03-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsmandadero', '0006_alter_requestmanager_mander_id_mander'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='model_vehicle',
            field=models.CharField(max_length=4),
        ),
    ]
