# Generated by Django 5.0.2 on 2024-03-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsmandadero', '0007_alter_vehicle_model_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image_vehicle',
            field=models.ImageField(max_length=255, null=True, upload_to='imgVehicles'),
        ),
    ]
