# Generated by Django 5.0.2 on 2024-03-05 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsmandadero', '0008_alter_vehicle_image_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='user_id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wsmandadero.user'),
        ),
        migrations.AlterField(
            model_name='mander',
            name='cc_mander',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='mander',
            name='user_id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wsmandadero.user', unique=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='service_id_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wsmandadero.service'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wsmandadero.user'),
        ),
        migrations.AlterField(
            model_name='requestmanager',
            name='mander_id_mander',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wsmandadero.mander'),
        ),
        migrations.AlterField(
            model_name='requestmanager',
            name='request_id_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wsmandadero.request', unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_id_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wsmandadero.account', unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_vehicle',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='user_id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wsmandadero.user'),
        ),
    ]
