# Generated by Django 5.0.2 on 2024-03-05 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsmandadero', '0007_merge_20240304_1815'),
        ('wsmandadero', '0009_alter_document_user_id_user_alter_mander_cc_mander_and_more'),
    ]

    operations = [
    ]
