# Generated by Django 5.0.2 on 2024-02-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id_vehicle', models.AutoField(primary_key=True, serialize=False)),
                ('user_id_user', models.IntegerField()),
                ('brand_vehicle', models.CharField(max_length=20)),
                ('plate_vehicle', models.CharField(max_length=10)),
                ('model_vehicle', models.SmallIntegerField()),
                ('color_vehicle', models.CharField(max_length=45)),
                ('type_vehicle', models.CharField(choices=[('tipo1', 'Tipo 1'), ('tipo2', 'Tipo 2'), ('tipo3', 'Tipo 3')], max_length=10)),
                ('isverified_vehicle', models.BooleanField(default=False)),
                ('dateregister_vehicle', models.DateTimeField(auto_now_add=True)),
                ('dateupdate_vehicle', models.DateTimeField(auto_now=True)),
                ('dateverified_vehicle', models.DateTimeField(blank=True, null=True)),
                ('image_vehicle', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
            ],
        ),
    ]
