# Generated by Django 5.0.2 on 2024-02-08 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand_vehicle',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color_vehicle',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', message='El color solo puede contener letras.')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model_vehicle',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type_vehicle',
            field=models.CharField(choices=[('Automovil', 'Particular'), ('Camioneta', 'Tipo 2'), ('Chana', 'Tipo 3')], max_length=10),
        ),
    ]
