# Generated by Django 5.0.2 on 2024-02-08 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_vehicle_brand_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='color_vehicle',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', message='El color solo puede contener letras.')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model_vehicle',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type_vehicle',
            field=models.CharField(choices=[('Automovil', 'tipo de vehiculo'), ('tipo 1', 'Automovil'), ('tipo 2', 'Camioneta'), ('tipo 3', 'Chana')], max_length=10),
        ),
    ]
