# Generated by Django 5.0.2 on 2024-02-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_alter_vehicle_color_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand_vehicle',
            field=models.DateField(max_length=15),
        ),
    ]
