# Generated by Django 5.0.2 on 2024-02-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_alter_vehicle_brand_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type_vehicle',
            field=models.CharField(choices=[('Automovil', 'tipo de vehiculo'), ('Automovil', 'Automovil'), ('Camioneta', 'Camioneta'), ('Chana', 'Chana')], max_length=10),
        ),
    ]
